// backend-app/db/dummyData.js
const dummyData = () => {

  const account_heads_data = [
    //Sales
    {
      id: "Z101",
      trhed_hednm: "Sales Booking (+)",
      trhed_grpnm: "Sales",
      trhed_grtyp: "In",
      trhed_cntyp: "Customer",
    },
    {
      id: "Z102",
      trhed_hednm: "Sales Invoice (-)",
      trhed_grpnm: "Sales",
      trhed_grtyp: "Out",
      trhed_cntyp: "Customer",
    },
    {
      id: "Z103",
      trhed_hednm: "Sales Order (+)",
      trhed_grpnm: "Sales",
      trhed_grtyp: "In",
      trhed_cntyp: "Customer",
    },
    {
      id: "Z104",
      trhed_hednm: "Sales Return (-)",
      trhed_grpnm: "Sales",
      trhed_grtyp: "Out",
      trhed_cntyp: "Customer",
    },
    {
      id: "Z105",
      trhed_hednm: "Sales Customer Expense (+)",
      trhed_grpnm: "Sales",
      trhed_grtyp: "In",
      trhed_cntyp: "Customer",
    },
    {
      id: "Z106",
      trhed_hednm: "Sales Expense (-)",
      trhed_grpnm: "Sales",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z107",
      trhed_hednm: "Sales Discount (-)",
      trhed_grpnm: "Sales",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z108",
      trhed_hednm: "Sales VAT (+)",
      trhed_grpnm: "Sales",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    //Purchase
    {
      id: "Z201",
      trhed_hednm: "Purchase Booking (-)",
      trhed_grpnm: "Purchases",
      trhed_grtyp: "Out",
      trhed_cntyp: "Supplier",
    },
    {
      id: "Z202",
      trhed_hednm: "Purchase Invoice (+)",
      trhed_grpnm: "Purchases",
      trhed_grtyp: "In",
      trhed_cntyp: "Supplier",
    },
    {
      id: "Z203",
      trhed_hednm: "Purchase Order (-)",
      trhed_grpnm: "Purchases",
      trhed_grtyp: "Out",
      trhed_cntyp: "Supplier",
    },
    {
      id: "Z204",
      trhed_hednm: "Purchase Return (+)",
      trhed_grpnm: "Purchases",
      trhed_grtyp: "In",
      trhed_cntyp: "Supplier",
    },
    {
      id: "Z205",
      trhed_hednm: "Purchase Purchase Expense (-)",
      trhed_grpnm: "Purchases",
      trhed_grtyp: "Out",
      trhed_cntyp: "Supplier",
    },
    {
      id: "Z206",
      trhed_hednm: "Purchase Expense (-)",
      trhed_grpnm: "Purchases",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z207",
      trhed_hednm: "Purchase Discount (+)",
      trhed_grpnm: "Purchases",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z208",
      trhed_hednm: "Purchase VAT (+)",
      trhed_grpnm: "Purchases",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    //Inventory
    {
      id: "Z301",
      trhed_hednm: "Stock Out (-)",
      trhed_grpnm: "Inventory",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z302",
      trhed_hednm: "Stock In (+)",
      trhed_grpnm: "Inventory",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    //Income
    {
      id: "Z401",
      trhed_hednm: "Gain (+)",
      trhed_grpnm: "Income",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z402",
      trhed_hednm: "Salary Deduction (+)",
      trhed_grpnm: "Income",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z403",
      trhed_hednm: "Rent Advance Received (+)",
      trhed_grpnm: "Income",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z404",
      trhed_hednm: "Rent Adjustment (+)",
      trhed_grpnm: "Income",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z405",
      trhed_hednm: "Bank Profit (+)",
      trhed_grpnm: "Income",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z406",
      trhed_hednm: "Loan Taken (+)",
      trhed_grpnm: "Income",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z407",
      trhed_hednm: "Deposit (+)",
      trhed_grpnm: "Income",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z408",
      trhed_hednm: "Asset Sale (+)",
      trhed_grpnm: "Assets",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z409",
      trhed_hednm: "Other Income (+)",
      trhed_grpnm: "Income",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
    //Expense
    {
      id: "Z501",
      trhed_hednm: "Loss (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z502",
      trhed_hednm: "Salary Payment (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z503",
      trhed_hednm: "Rent Advance Payment (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z504",
      trhed_hednm: "Rent Payment (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z505",
      trhed_hednm: "Electricity Bill (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z506",
      trhed_hednm: "Internet Bill (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z507",
      trhed_hednm: "Transport Payment (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z508",
      trhed_hednm: "Bank Charges (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z509",
      trhed_hednm: "Tax Payment (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z510",
      trhed_hednm: "Maintenance Payment (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z511",
      trhed_hednm: "Loan Payment (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z512",
      trhed_hednm: "Asset Purchase (-)",
      trhed_grpnm: "Assets",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z513",
      trhed_hednm: "Other Expense (-)",
      trhed_grpnm: "Expense",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z514",
      trhed_hednm: "Withdraw (-)",
      trhed_grpnm: "Income",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    //Transfer
    {
      id: "Z601",
      trhed_hednm: "Transfer Out (-)",
      trhed_grpnm: "Transfer",
      trhed_grtyp: "Out",
      trhed_cntyp: "Internal",
    },
    {
      id: "Z602",
      trhed_hednm: "Transfer In (+)",
      trhed_grpnm: "Transfer",
      trhed_grtyp: "In",
      trhed_cntyp: "Internal",
    },
  ];

  return { account_heads_data };
};

module.exports = dummyData;