import { resolveMenuIcon } from "@/utils/menuIcons";

/* ─── Hierarchical App Data: Module > Groups > Menu ─────── */

/** Build a menu item object from a data entry */
export const toMenu = (m) => ({
  id: m.id,
  menus_mname: m.name,
  menus_color: m.color,
  menus_micon: resolveMenuIcon(m.icon),
  menus_micon_name: m.icon,
  menus_odrby: m.order,
  menus_mlink: m.link,
  menus_mdesc: m.desc,
});

export const appModules = [
  {
    id: "M00",
    name: "Recent",
    icon: "Home",
    color: "#7c3aed",
    order: 0,
    menus: [],
  },
  {
    id: "M01",
    name: "Settings",
    icon: "Settings",
    color: "#7c3aed",
    order: 1,
    groups: [
      {
        id: "G01",
        name: "General",
        order: 1,
        menus: [
          {
            id: "M01-G01-M001",
            name: "Work Space",
            color: "#7c3aed",
            icon: "Info",
            order: 1,
            link: "/bsuite/workspace",
            desc: "Work Space",
          },
          {
            id: "M01-G01-M002",
            name: "Home",
            color: "#7c3aed",
            icon: "Home",
            order: 1,
            link: "/",
            desc: "Return to dashboard overview",
          },
          {
            id: "M01-G01-M003",
            name: "General",
            color: "#7c3aed",
            icon: "Settings",
            order: 2,
            link: "/settings/general",
            desc: "Application preferences and theme color",
          },
        ],
      },
      {
        id: "G02",
        name: "Setup",
        order: 2,
        menus: [
          {
            id: "M01-G02-M001",
            name: "Departments",
            color: "#7c3aed",
            icon: "Home",
            order: 8,
            link: "/settings/departments",
            desc: "Manage organizational departments",
          },
          {
            id: "M01-G02-M002",
            name: "Sections",
            color: "#7c3aed",
            icon: "Home",
            order: 9,
            link: "/settings/sections",
            desc: "Configure department sections",
          },
          {
            id: "M01-G02-M003",
            name: "Grid Options",
            color: "#7c3aed",
            icon: "Bar",
            order: 10,
            link: "/settings/grid-options",
            desc: "Configure module table column visibility",
          },
        ],
      },
    ],
  },
  {
    id: "M02",
    name: "Purchase",
    icon: "Purchase",
    color: "#06b6d4",
    order: 2,
    groups: [
      {
        id: "G01",
        name: "Setup",
        order: 1,
        menus: [
          {
            id: "M02-G01-M001",
            name: "Purchase Bunldes",
            color: "#06b6d4",
            icon: "Purchase",
            order: 1,
            link: "/purchase/setup/suppliers",
            desc: "Manage vendor and supplier profiles",
          },
        ],
      },
      {
        id: "G02",
        name: "Transactions",
        order: 2,
        menus: [
          {
            id: "M02-G02-M001",
            name: "MRR (Direct)",
            color: "#06b6d4",
            icon: "Purchase",
            order: 1,
            link: "/purchase/mrr-direct",
            desc: "Record received goods and inspections",
          },
          {
            id: "M02-G02-M002",
            name: "Purchase Returns",
            color: "#06b6d4",
            icon: "Purchase",
            order: 3,
            link: "/purchase/returns",
            desc: "Handle suppliers return requests",
          },
        ],
      },
    ],
  },
  {
    id: "M03",
    name: "Sales",
    icon: "Sales",
    color: "#eab308",
    order: 3,
    groups: [
      {
        id: "G01",
        name: "Setup",
        order: 1,
        menus: [
          {
            id: "M03-G01-M001",
            name: "Sales Targets",
            color: "#eab308",
            icon: "Sales",
            order: 1,
            link: "/sales/setup/targets",
            desc: "Set revenue and volume targets",
          },
        ],
      },
      {
        id: "G02",
        name: "Transactions",
        order: 2,
        menus: [
          {
            id: "M03-G02-M001",
            name: "Sales Invoice",
            color: "#eab308",
            icon: "Sales",
            order: 1,
            link: "/sales/invoice",
            desc: "Process customer sales invoice",
          },
          {
            id: "M03-G02-M002",
            name: "Deliveries",
            color: "#eab308",
            icon: "Sales",
            order: 2,
            link: "/sales/deliveries",
            desc: "Manage delivery and dispatch records",
          },
          {
            id: "M03-G02-M003",
            name: "Sales Returns",
            color: "#eab308",
            icon: "Sales",
            order: 3,
            link: "/sales/returns",
            desc: "Handle customer return requests",
          },
        ],
      },
    ],
  },
  {
    id: "M04",
    name: "Inventory",
    icon: "Box",
    color: "#f97316",
    order: 4,
    groups: [
      {
        id: "G01",
        name: "Setup",
        order: 1,
        menus: [
          {
            id: "M04-G01-M001",
            name: "Brands",
            color: "#f97316",
            icon: "Box",
            order: 1,
            link: "/inventory/setup/brands",
            desc: "Manage product brand profiles",
          },
          {
            id: "M04-G01-M002",
            name: "Categories",
            color: "#f97316",
            icon: "Box",
            order: 2,
            link: "/inventory/setup/categories",
            desc: "Organize product categories",
          },
          {
            id: "M04-G01-M003",
            name: "Groups",
            color: "#f97316",
            icon: "Box",
            order: 3,
            link: "/inventory/setup/groups",
            desc: "Manage product group classifications",
          },
          {
            id: "M04-G01-M004",
            name: "Units",
            color: "#f97316",
            icon: "Box",
            order: 4,
            link: "/inventory/setup/units",
            desc: "Configure measurement units",
          },
          {
            id: "M04-G01-M005",
            name: "Items",
            color: "#f97316",
            icon: "Box",
            order: 5,
            link: "/inventory/setup/items",
            desc: "Manage inventory item records",
          },
          {
            id: "M04-G01-M006",
            name: "Stock",
            color: "#f97316",
            icon: "Box",
            order: 6,
            link: "/inventory/stock",
            desc: "Manage inventory item records",
          },
        ],
      },
    ],
  },
  {
    id: "M05",
    name: "Manufacturing",
    icon: "Manufacture",
    color: "#22c55e",
    order: 5,
    groups: [
      {
        id: "G01",
        name: "Setup",
        order: 1,
        menus: [
          {
            id: "M05-G01-M001",
            name: "Productions",
            color: "#22c55e",
            icon: "Manufacture",
            order: 1,
            link: "/manufacturing/setup/productions",
            desc: "Track and manage manufacturing runs",
          },
          {
            id: "M05-G01-M002",
            name: "BOM",
            color: "#22c55e",
            icon: "Manufacture",
            order: 2,
            link: "/manufacturing/setup/bom",
            desc: "Bill of Materials structure",
          },
        ],
      },
      {
        id: "G02",
        name: "Operations",
        order: 2,
        menus: [
          {
            id: "M05-G02-M001",
            name: "Process",
            color: "#22c55e",
            icon: "Manufacture",
            order: 3,
            link: "/manufacturing/process",
            desc: "Manage production process flows",
          },
        ],
      },
    ],
  },
  {
    id: "M06",
    name: "CRM",
    icon: "CRM",
    color: "#3b82f6",
    order: 6,
    groups: [
      {
        id: "G01",
        name: "Contacts",
        order: 1,
        menus: [
          {
            id: "M06-G01-M001",
            name: "Contacts",
            color: "#3b82f6",
            icon: "CRM",
            order: 1,
            link: "/M06/contacts",
            desc: "Manage business contact records",
          },
        ],
      },
      {
        id: "G02",
        name: "Setup",
        order: 2,
        menus: [
          {
            id: "M06-G02-M001",
            name: "Territories",
            color: "#3b82f6",
            icon: "CRM",
            order: 2,
            link: "/crm/setup/territories",
            desc: "Define sales territory boundaries",
          },
          {
            id: "M06-G02-M002",
            name: "Thana / Area",
            color: "#3b82f6",
            icon: "CRM",
            order: 3,
            link: "/crm/setup/thana-areas",
            desc: "Manage thana and area zones",
          },
          {
            id: "M06-G02-M003",
            name: "District / Zone",
            color: "#3b82f6",
            icon: "CRM",
            order: 4,
            link: "/crm/setup/district-zones",
            desc: "Configure district and zone regions",
          },
        ],
      },
    ],
  },
  {
    id: "M07",
    name: "HRMS",
    icon: "HR",
    color: "#ec4899",
    order: 7,
    groups: [
      {
        id: "G01",
        name: "Setup",
        order: 1,
        menus: [
          {
            id: "M07-G01-M001",
            name: "Working Shift",
            color: "#ec4899",
            icon: "HR",
            order: 1,
            link: "/hrms/setup/work-shifts",
            desc: "Set employee work shift schedules",
          },
          {
            id: "M07-G01-M002",
            name: "Holidays",
            color: "#ec4899",
            icon: "HR",
            order: 2,
            link: "/hrms/setup/holidays",
            desc: "Manage holiday calendar entries",
          },
          {
            id: "M07-G01-M003",
            name: "Designations",
            color: "#ec4899",
            icon: "HR",
            order: 3,
            link: "/hrms/setup/designations",
            desc: "Manage designations",
          },
        ],
      },
    ],
  },
  {
    id: "M08",
    name: "Accounts",
    icon: "Accounts",
    color: "#8b5cf6",
    order: 8,
    groups: [
      {
        id: "G01",
        name: "Setup",
        order: 1,
        menus: [
          {
            id: "M08-G01-M001",
            name: "Chart of Accounts",
            color: "#8b5cf6",
            icon: "Accounts",
            order: 1,
            link: "/accounts/setup/chart-of-accounts",
            desc: "Configure the chart of accounts",
          },
          {
            id: "M08-G01-M002",
            name: "Fiscal Years",
            color: "#8b5cf6",
            icon: "Accounts",
            order: 2,
            link: "/accounts/setup/fiscal-years",
            desc: "Manage fiscal year periods",
          },
          {
            id: "M08-G01-M003",
            name: "Accounting Periods",
            color: "#8b5cf6",
            icon: "Accounts",
            order: 3,
            link: "/accounts/setup/accounting-periods",
            desc: "Set accounting period date ranges",
          },
          {
            id: "M08-G01-M004",
            name: "Party Accounts",
            color: "#8b5cf6",
            icon: "Users",
            order: 4,
            link: "/accounts/setup/parties",
            desc: "Manage party account profiles",
          },
          {
            id: "M08-G01-M005",
            name: "Party Routing",
            color: "#8b5cf6",
            icon: "Users",
            order: 5,
            link: "/accounts/setup/party-network",
            desc: "Party accounts network routing",
          },
        ],
      },
      {
        id: "G02",
        name: "Transactions",
        order: 2,
        menus: [
          {
            id: "M08-G02-M001",
            name: "Journals",
            color: "#8b5cf6",
            icon: "Activity",
            order: 1,
            link: "/accounts/journals",
            desc: "Record financial journal entries",
          },
          {
            id: "M08-G02-M002",
            name: "Payables",
            color: "#8b5cf6",
            icon: "Activity",
            order: 2,
            link: "/accounts/payables",
            desc: "Record Payables journal entries",
          },
          {
            id: "M08-G02-M003",
            name: "Receivables",
            color: "#8b5cf6",
            icon: "Activity",
            order: 3,
            link: "/accounts/receivables",
            desc: "Record Receivables journal entries",
          },
        ],
      },
      {
        id: "G03",
        name: "Reports",
        order: 3,
        menus: [
          {
            id: "M08-G03-M001",
            name: "Financial Statements",
            color: "#8b5cf6",
            icon: "File",
            order: 1,
            link: "/accounts/reports/fstatements",
            desc: "Financial Statements",
          },
        ],
      },
    ],
  },
  {
    id: "M09",
    name: "Examples",
    icon: "Activity",
    color: "#f59e0b",
    order: 9,
    groups: [
      {
        id: "G01",
        name: "Reports",
        order: 1,
        menus: [
          {
            id: "M09-G01-M001",
            name: "Reports",
            color: "#f59e0b",
            icon: "File",
            order: 1,
            link: "/reports",
            desc: "View and generate system reports",
          },
        ],
      },
      {
        id: "G02",
        name: "Transactions",
        order: 2,
        menus: [
          {
            id: "M09-G02-M001",
            name: "Transactions",
            color: "#f59e0b",
            icon: "File",
            order: 1,
            link: "/transactions",
            desc: "Browse all system transactions",
          },
        ],
      },
      {
        id: "G03",
        name: "Admin",
        order: 3,
        menus: [
          {
            id: "M09-G03-M001",
            name: "Users",
            color: "#f59e0b",
            icon: "File",
            order: 1,
            link: "/users",
            desc: "Manage system user accounts",
          },
          {
            id: "M09-G03-M002",
            name: "Settings",
            color: "#f59e0b",
            icon: "File",
            order: 1,
            link: "/settings",
            desc: "Configure system preferences",
          },
        ],
      },
      {
        id: "G04",
        name: "Examples",
        order: 4,
        menus: [
          {
            id: "M09-G04-M001",
            name: "UI Examples",
            color: "#f59e0b",
            icon: "File",
            order: 1,
            link: "/examples",
            desc: "Browse UI component examples",
          },
          {
            id: "M09-G04-M002",
            name: "TreeView Examples",
            color: "#22c55e",
            icon: "File",
            order: 2,
            link: "/examples/treeview",
            desc: "Explore TreeView component demos",
          },
        ],
      },
      {
        id: "G05",
        name: "Navigation",
        order: 5,
        menus: [
          {
            id: "M09-G05-M001",
            name: "Modules",
            color: "#f59e0b",
            icon: "File",
            order: 1,
            link: "/M01/modules",
            desc: "Browse all application modules",
          },
        ],
      },
    ],
  },
];

// Build the flat menus array used for search & recent menus
export const menus = appModules.flatMap((mod) => {
  const items = [];
  if (mod.groups) {
    for (const g of mod.groups) {
      for (const m of g.menus) {
        items.push({
          ...toMenu(m),
          menus_mgrup: g.name,
          menus_mgrup_id: g.id,
          menus_mgrup_order: g.order,
        });
      }
    }
  }
  return items;
});

// Topbar navigation items
export const navItems = [
  { to: "/", label: "Dashboard", icon: "◉" },
  { to: "/users", label: "Users", icon: "◐" },
  { to: "/transactions", label: "Transactions", icon: "◈" },
  { to: "/reports", label: "Reports", icon: "▣" },
  { to: "/settings", label: "Settings", icon: "⚙" },
  { to: "/examples", label: "Examples", icon: "✦" },
  { to: "/notifications", label: "Notifications", icon: "◉" },
  { to: "/M06/contacts", label: "Contacts", icon: "⊕" },
  { to: "/M08/chart-of-accounts", label: "COA", icon: "◐" },
  { to: "/M08/accounting-periods", label: "Periods", icon: "◈" },
  { to: "/M08/fiscal-years", label: "Fiscal Yr", icon: "▣" },
  { to: "/M08/parties", label: "Parties", icon: "⊕" },
  { to: "/M01/modules", label: "Modules", icon: "⊞" },
];

// Menu entry used by the topbar launcher to open the module page (/bsuite/modules)
// as a popup — the popup renders all modules and menus, and clicking a menu
// navigates to that menu's URL.
export const modulesMenu = {
  ...toMenu({
    id: "M01-MODULES",
    name: "Modules",
    color: "#7c3aed",
    icon: "Dashboard",
    order: 0,
    link: "/bsuite/modules",
    desc: "Browse all application modules",
  }),
  menus_mgrup: "Navigation",
  menus_mgrup_id: "G00",
  menus_mgrup_order: 0,
};
