/* generated by : Gemeni Pro 3.1
prompt from: ibnekayesh91@gmail.com */
const hoursGroup = document.getElementById("hours-group");
const minutesGroup = document.getElementById("minutes-group");
const secondsGroup = document.getElementById("seconds-group");

const ampmText = document.getElementById("ampm-text");
const dateText = document.getElementById("date-text");

const wrapper = document.getElementById("clockWrapper");

const RH = 140;
const RM = 260;
const RS = 380;

let lastSecond = 0;
let secondTurns = 0;

function polar(r, a) {
  const rad = (a * Math.PI) / 180;

  return {
    x: r * Math.cos(rad),
    y: r * Math.sin(rad),
  };
}

/* BUILD HOUR WHEEL */
for (let i = 1; i <= 12; i++) {
  const a = i * 30;
  const pos = polar(RH, a);
  const t = document.createElementNS("http://www.w3.org/2000/svg", "text");

  t.setAttribute("class", "hour-text");
  t.setAttribute("x", pos.x);
  t.setAttribute("y", pos.y);
  t.setAttribute("transform", `rotate(${a},${pos.x},${pos.y})`);  
  t.textContent = i;
  hoursGroup.appendChild(t);
}

/* BUILD MINUTE WHEEL */

for (let i = 0; i < 60; i++) {
  const a = i * 6;
  const pos = polar(RM, a);

  const t = document.createElementNS("http://www.w3.org/2000/svg", "text");
  t.setAttribute("class", "minute-text");
  t.setAttribute("x", pos.x);
  t.setAttribute("y", pos.y);
  t.setAttribute("transform", `rotate(${a},${pos.x},${pos.y})`);
  t.textContent = i.toString().padStart(2, "0");
  minutesGroup.appendChild(t);
}

/* BUILD SECOND WHEEL */

for (let i = 0; i < 60; i++) {
  const a = i * 6;
  const pos = polar(RS, a);

  const t = document.createElementNS("http://www.w3.org/2000/svg", "text");
  t.setAttribute("class", "second-text");
  t.setAttribute("x", pos.x);
  t.setAttribute("y", pos.y);
  t.setAttribute("transform", `rotate(${a},${pos.x},${pos.y})`);
  t.textContent = i.toString().padStart(2, "0");
  secondsGroup.appendChild(t);
}

const months = [
  "JAN",
  "FEB",
  "MAR",
  "APR",
  "MAY",
  "JUN",
  "JUL",
  "AUG",
  "SEP",
  "OCT",
  "NOV",
  "DEC",
];

function highlight(group, cls, index) {
  group.querySelectorAll("text").forEach((e, i) => {
    e.classList.remove(cls);

    if (i === index) e.classList.add(cls);
  });
}

function update() {
  const now = new Date();
  const ms = now.getMilliseconds();
  const s = now.getSeconds();
  const m = now.getMinutes();
  const h24 = now.getHours();
  const h = h24 % 12 || 12;

  /* AM PM */
  ampmText.textContent = h24 >= 12 ? "PM" : "AM";

  /* DATE */
  dateText.textContent = `${now.getDate()} ${months[now.getMonth()]} ${now.getFullYear()}`;

  /* SECOND SMOOTH ROTATION */
  const sec = s + ms / 1000;
  if (s < lastSecond) {
    secondTurns += 60;
  }
  lastSecond = s;

  const continuousSeconds = secondTurns + sec;
  secondsGroup.setAttribute("transform", `rotate(${-continuousSeconds * 6})`);

  /* MINUTE SNAP */
  const minProgress = m;
  minutesGroup.setAttribute("transform", `rotate(${-minProgress * 6})`);

  /* HOUR SNAP */
  const hrProgress = h;
  hoursGroup.setAttribute("transform", `rotate(${-hrProgress * 30})`);

  /* ACTIVE HIGHLIGHT */
  highlight(secondsGroup, "active-second", s);
  highlight(minutesGroup, "active-minute", m);
  highlight(hoursGroup, "active-hour", h - 1);

  requestAnimationFrame(update);
}

requestAnimationFrame(update);

/* MOUSE PARALLAX */
document.addEventListener("mousemove", (e) => {
  const x = (e.clientX / window.innerWidth - 0.5) * 20;
  const y = (e.clientY / window.innerHeight - 0.5) * 10;
  wrapper.style.transform = `translateY(-50%) perspective(900px) rotateY(${x}deg) rotateX(${-y}deg)`;
});
