export const appCatalog = [
  {
    id: "sales",
    name: "Sales",
    icon: "📊",
    child: [
      {
        id: "sales-invoice",
        name: "Sales Invoice",
        icon: "📄",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "sales-order",
        name: "Sales Order",
        icon: "📋",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "sales-quotation",
        name: "Quotation",
        icon: "💬",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "sales-report",
        name: "Sales Report",
        icon: "📈",
        forms: "SalesPage",
        module: "sales",
        size: "full",
      },
    ],
  },
  {
    id: "purchase",
    name: "Purchase",
    icon: "🛒",
    child: [
      {
        id: "purchase-invoice",
        name: "Purchase Invoice",
        icon: "📄",
        forms: "PurchasePage",
        module: "purchase",
        size: "medium",
      },
      {
        id: "purchase-order",
        name: "Purchase Order",
        icon: "📋",
        forms: "PurchasePage",
        module: "purchase",
        size: "medium",
      },
      {
        id: "purchase-report",
        name: "Purchase Report",
        icon: "📈",
        forms: "PurchasePage",
        module: "purchase",
        size: "full",
      },
    ],
  },
  {
    id: "inventory",
    name: "Inventory",
    icon: "📦",
    child: [
      {
        id: "inventory-stock",
        name: "Stock Ledger",
        icon: "📋",
        forms: "InventoryPage",
        module: "inventory",
        size: "medium",
      },
      {
        id: "inventory-adjustment",
        name: "Stock Adjustment",
        icon: "🔄",
        forms: "InventoryPage",
        module: "inventory",
        size: "medium",
      },
      {
        id: "inventory-transfer",
        name: "Stock Transfer",
        icon: "🚚",
        forms: "InventoryPage",
        module: "inventory",
        size: "medium",
      },
      {
        id: "inventory-report",
        name: "Inventory Report",
        icon: "📈",
        forms: "InventoryPage",
        module: "inventory",
        size: "full",
      },
    ],
  },
  {
    id: "accounting",
    name: "Accounting",
    icon: "💰",
    child: [
      {
        id: "acc-journal",
        name: "Journal Entry",
        icon: "📝",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "acc-ledger",
        name: "General Ledger",
        icon: "📋",
        forms: "SalesPage",
        module: "sales",
        size: "full",
      },
      {
        id: "acc-trial",
        name: "Trial Balance",
        icon: "⚖️",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
    ],
  },
  {
    id: "human-resources",
    name: "Human Resources",
    icon: "👥",
    child: [
      {
        id: "hr-employee",
        name: "Employees",
        icon: "👤",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "hr-payroll",
        name: "Payroll",
        icon: "💵",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "hr-attendance",
        name: "Attendance",
        icon: "✓",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
    ],
  },
  {
    id: "production",
    name: "Production",
    icon: "🏭",
    child: [
      {
        id: "prod-bom",
        name: "Bill of Materials",
        icon: "📋",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "prod-order",
        name: "Production Order",
        icon: "🏗️",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "prod-report",
        name: "Production Report",
        icon: "📊",
        forms: "SalesPage",
        module: "sales",
        size: "full",
      },
    ],
  },
  {
    id: "quality",
    name: "Quality Control",
    icon: "✅",
    child: [
      {
        id: "qc-inspection",
        name: "Inspection",
        icon: "🔍",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "qc-defect",
        name: "Defect Log",
        icon: "⚠️",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
    ],
  },
  {
    id: "projects",
    name: "Projects",
    icon: "📐",
    child: [
      {
        id: "proj-list",
        name: "Project List",
        icon: "📋",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "proj-task",
        name: "Tasks",
        icon: "✓",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "proj-gantt",
        name: "Gantt Chart",
        icon: "📊",
        forms: "SalesPage",
        module: "sales",
        size: "full",
      },
    ],
  },
  {
    id: "crm",
    name: "CRM",
    icon: "🤝",
    child: [
      {
        id: "crm-customer",
        name: "Customers",
        icon: "👥",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "crm-lead",
        name: "Leads",
        icon: "🎯",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "crm-campaign",
        name: "Campaigns",
        icon: "📢",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
    ],
  },
  {
    id: "reports",
    name: "Reports",
    icon: "📊",
    child: [
      {
        id: "rpt-dashboard",
        name: "Dashboard",
        icon: "📈",
        forms: "SalesPage",
        module: "sales",
        size: "full",
      },
      {
        id: "rpt-custom",
        name: "Custom Report",
        icon: "⚙️",
        forms: "SalesPage",
        module: "sales",
        size: "full",
      },
    ],
  },
  {
    id: "setup",
    name: "Setup",
    icon: "⚙️",
    child: [
      {
        id: "setup-company",
        name: "Company",
        icon: "🏢",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "setup-desktop",
        name: "Desktop",
        icon: "🖥️",
        forms: "SetupPage",
        module: "setup",
        size: "medium",
      },
      {
        id: "setup-users",
        name: "Users",
        icon: "👤",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "setup-security",
        name: "Security",
        icon: "🔒",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
    ],
  },
  {
    id: "tools",
    name: "Tools",
    icon: "🛠️",
    child: [
      {
        id: "tools-backup",
        name: "Backup",
        icon: "💾",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "tools-import",
        name: "Import Data",
        icon: "📥",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
      {
        id: "tools-export",
        name: "Export Data",
        icon: "📤",
        forms: "SalesPage",
        module: "sales",
        size: "medium",
      },
    ],
  },
];
