CREATE TABLE IF NOT EXISTS t_feature_table (
    id VARCHAR(50) PRIMARY KEY,
    feature_id VARCHAR(50) NOT NULL,
    table_id VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);