CREATE TABLE IF NOT EXISTS t_task (
    id VARCHAR(50) PRIMARY KEY,
    feature_id VARCHAR(50) NOT NULL,
    task_name VARCHAR(255) NOT NULL,
    is_done BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);