// Root level menus and child menus configurations with their default WFE sizes (small, medium, fullscreen)
export const rootMenus = [
  {
    id: "sales-manager",
    title: "Sales Manager",
    icon: "💼",
    color: "#0078d4",
    path: "System Root > Sales Manager",
    children: [
      {
        id: "sales-orders",
        title: "Sales Orders",
        icon: "📝",
        desc: "Manage invoices and sales transactions",
        type: "page",
        pageKey: "SOPage",
        defaultSize: "medium",
        group: "Transactions",
      },
      {
        id: "customers",
        title: "Customers Directory",
        icon: "👥",
        desc: "View customer accounts and balances",
        type: "page",
        pageKey: "CustomersPage",
        defaultSize: "small",
        group: "Transactions",
      },
      {
        id: "promotions-setup",
        title: "Promotions Setup",
        icon: "🎟️",
        desc: "Configure coupons, discounts, and campaigns",
        type: "page",
        pageKey: "PromotionsSetup",
        defaultSize: "medium",
        group: "Setup",
      },
      {
        id: "price-lists",
        title: "Price Lists",
        icon: "💲",
        desc: "Set customer/vendor custom pricing",
        type: "page",
        pageKey: "PriceLists",
        defaultSize: "medium",
        group: "Setup",
      },
      {
        id: "sales-report",
        title: "Sales Report",
        icon: "📊",
        desc: "Track sales performance and trends",
        type: "page",
        pageKey: "SalesReport",
        defaultSize: "fullscreen",
        group: "Reports",
      },
    ],
  },
  {
    id: "purchase-manager",
    title: "Purchase Manager",
    icon: "🛒",
    color: "#107c41",
    path: "System Root > Purchase Manager",
    children: [
      {
        id: "purchase-orders",
        title: "Purchase Orders",
        icon: "💳",
        desc: "Create and track supply purchase orders",
        type: "page",
        pageKey: "POPage",
        defaultSize: "fullscreen",
        group: "Transactions",
      },
      {
        id: "vendors",
        title: "Vendor Directory",
        icon: "🏬",
        desc: "Manage supplier contacts and ratings",
        type: "page",
        pageKey: "VendorsPage",
        defaultSize: "medium",
        group: "Transactions",
      },
      {
        id: "purchase-report",
        title: "Purchase Report",
        icon: "📈",
        desc: "Track purchase performance and trends",
        type: "page",
        pageKey: "PurchaseReport",
        defaultSize: "fullscreen",
        group: "Reports",
      },
    ],
  },
  {
    id: "inventory-manager",
    title: "Inventory Manager",
    icon: "📦",
    color: "#d83b01",
    path: "System Root > Inventory Manager",
    children: [
      {
        id: "stock-levels",
        title: "Stock Ledger",
        icon: "🏷️",
        desc: "Monitor safety thresholds and restock items",
        type: "page",
        pageKey: "StockPage",
        defaultSize: "medium",
        group: "Operations",
      },
      {
        id: "inventory-report",
        title: "Inventory Report",
        icon: "📉",
        desc: "Analyze stock turn-over and aging",
        type: "page",
        pageKey: "InventoryReport",
        defaultSize: "medium",
        group: "Reports",
      },
    ],
  },
  {
    id: "system-settings",
    title: "System Settings",
    icon: "⚙️",
    color: "#8764b8",
    path: "System Root > Control Panel > Settings",
    children: [
      {
        id: "profile-settings",
        title: "User Settings",
        icon: "👤",
        desc: "Modify your workspace preferences",
        type: "page",
        pageKey: "ProfileSettings",
        defaultSize: "small",
        group: "Account",
      },
      {
        id: "system-settings-child",
        title: "System Settings",
        icon: "⚙️",
        desc: "Configure global enterprise variables",
        type: "page",
        pageKey: "SettingsPage",
        defaultSize: "medium",
        group: "System",
      },
    ],
  },
  {
    id: "Notifications",
    title: "Notifications",
    icon: "🔔",
    color: "#0078d4",
    path: "System Root > Notifications",
    children: [
      {
        id: "notifications",
        title: "Notifications",
        desc: "Notifications log",
        type: "page",
        pageKey: "NotificationPage",
        defaultSize: "medium",
        group: "Notifications",
      },
    ],
  },
  {
    id: "Preferences",
    title: "Preferences",
    icon: "🔔",
    color: "#0078d4",
    path: "System Root > Preferences",
    children: [
      {
        id: "Preferences",
        title: "Preferences",
        desc: "Preferences log",
        type: "page",
        pageKey: "NotificationPage",
        defaultSize: "medium",
        group: "Preferences",
      },
    ],
  },
];
